server:
  port: 9099
spring:
  application:
    name: FeignDemoApplication
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/